export { useEditarPaciente } from './useEditarPaciente'
export { usePerfilPaciente } from './usePerfilPaciente'
export { useDashboard } from './useDashboard'
export type { DashboardData } from './useDashboard'
export { useRelatorioAdesaoMedicamento } from './useRelatorioAdesaoMedicamento'
export { useRelatorioOrientacaoFuncional } from './useRelatorioOrientacaoFuncional'
