export { Home } from './Home'
export { Login } from './Login'
export { Profissionais } from './Profissionais'
export { Pacientes } from './Pacientes'
export { MeuPerfil } from './MeuPerfil'
export { RecuperarSenha } from './RecuperarSenha'
export { ResetPassword } from './ResetPassword'